# -*- coding: utf-8 -*-
"""Copy of CItyChatbotPopulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E5y8xFbKbqlmrTVmoQa5rcTVR1sUYis_
"""

!pip install flask-ngrok
from flask_ngrok import run_with_ngrok

import threading
import json
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from flask import Flask, request, jsonify
from IPython.display import display, Image

app = Flask(__name__)

# Sample city data
data = {
    "population": [
        {"year": 2000, "population": 500000},
        {"year": 2005, "population": 600000},
        {"year": 2010, "population": 750000},
        {"year": 2015, "population": 900000},
        {"year": 2020, "population": 1100000}
    ]
}

def generate_population_plot():
    df = pd.DataFrame(data['population'])
    sns.lineplot(x='year', y='population', data=df, marker='o')
    plt.title("City Population Growth")
    plt.xlabel("Year")
    plt.ylabel("Population")
    plt.grid()
    plt.savefig("population.png")
    plt.close()

@app.route('/chat', methods=['POST'])
def chat():
    user_input = request.json.get("message", "").lower()

    if "population" in user_input:
        generate_population_plot()
        return jsonify({"response": "Here is the city population growth graph.", "image": "population.png"})
    else:
        return jsonify({"response": "Ask about population to see a visualization!"})

def run_app():
    app.run(port=5000, debug=False, use_reloader=False)

flask_thread = threading.Thread(target=run_app)
flask_thread.start()

import requests

response = requests.post("http://127.0.0.1:5000/chat", json={"message": "Show me the population trend"})
data = response.json()
print(data["response"])

# Display the generated image
if "image" in data:
    display(Image("population.png"))